/**
 * Output writer — assembles all pipeline artifacts into file content strings
 * and writes them to disk.
 *
 * buildOutputs()  → pure function, returns all five artifact strings
 * writeOutputs()  → the only function with side effects (fs.writeFile calls)
 *
 * The business.ts template is the most complex output: it must produce valid
 * TypeScript that satisfies the Business interface in @/types/index.ts, using
 * the real Lucide icon components (not the string names used internally in the
 * pipeline). String icon names like 'ShieldCheck' are converted to import
 * references in the generated file.
 */

import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

import type {
  PipelineResult,
  OutputFiles,
  PipelineProofPoint,
  PipelineBenefit,
  PipelineServiceEntry,
  PipelineFAQItem,
  PipelineStat,
  ConfidenceReport,
  ReviewQueueItem,
  DesignBrief,
  PhotoBrief,
  PhotoShot,
} from '../types';

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Pure function: build all five output artifacts from a pipeline result.
 * Returns strings ready to write to disk — no I/O.
 */
export function buildOutputs(result: PipelineResult): OutputFiles {
  return {
    'business.ts': generateBusinessTs(result),
    '_confidence.json': generateConfidenceJson(result.confidenceReport),
    '_review_queue.md': generateReviewQueueMd(result.reviewQueue),
    '_design_brief.md': generateDesignBriefMd(result.designBrief, result.rawData.name),
    '_photo_brief.md': generatePhotoBriefMd(result.photoBrief, result.rawData.name),
  };
}

/**
 * Write all five output files to the client's data directory.
 *
 * @param outputs   - From buildOutputs()
 * @param clientSlug - e.g. 'martinez-landscaping'
 * @param rootDir   - Project root, defaults to process.cwd()
 */
export async function writeOutputs(
  outputs: OutputFiles,
  clientSlug: string,
  rootDir: string = process.cwd(),
): Promise<void> {
  const dir = join(rootDir, 'src', 'data', 'businesses', clientSlug);
  await mkdir(dir, { recursive: true });

  await Promise.all(
    (Object.entries(outputs) as Array<[keyof OutputFiles, string]>).map(([filename, content]) =>
      writeFile(join(dir, filename), content, 'utf-8'),
    ),
  );
}

// ─── business.ts template ─────────────────────────────────────────────────────

function generateBusinessTs(result: PipelineResult): string {
  const { rawData: d, generated: g } = result;

  // Collect all icon names used so we can build the import statement
  const iconNames = new Set<string>();
  g.proofPoints.value.forEach((p) => iconNames.add(p.iconName));
  g.benefits.value.forEach((b) => iconNames.add(b.iconName));
  g.services.value.forEach((s) => iconNames.add(s.iconName));

  const iconImport =
    iconNames.size > 0
      ? `import { ${[...iconNames].sort().join(', ')} } from 'lucide-react';\n`
      : '';

  const sc = g.sectionCopy.value;

  return `/**
 * ${d.name}
 * Generated by Summit Studio pipeline — ${new Date().toISOString().split('T')[0]}
 * Review flagged fields in _review_queue.md before going live.
 */

import type { Business } from '@/types';
${iconImport}
export const BUSINESS = {
  // ── Identity ──
  name: ${q(d.name)},
  slug: ${q(toSlug(d.name))},
  tagline: ${q(g.tagline.value)},
  logo: {
    primary: ${q(d.shortName ?? d.name)},
    secondary: ${q(d.category ?? 'Landscaping')},
    badge: ${q(d.shortName?.substring(0, 2).toUpperCase() ?? 'ML')},
  },
  seo: {
    title: ${q(`${d.name} — ${d.category ?? 'Landscaping'} in ${d.address?.city ?? d.serviceArea ?? 'Your Area'}`)},
    description: ${q(d.description ?? g.businessStory.value.mission)},
    keywords: [
${(d.services ?? []).slice(0, 6).map((s) => `      ${q(s.name.toLowerCase())},`).join('\n')}
      ${q((d.address?.city ?? 'local') + ' landscaping')},
    ],
    locale: 'en_US',
    type: 'website',
  },

  // ── Contact ──
  contact: {
    phone: ${q(d.phone ?? '')},
    phoneHref: ${q(d.phoneHref ?? '')},
    email: ${q(d.email ?? '')},
    emailHref: ${q(d.emailHref ?? '')},
    address: {
      street: ${q(d.address?.street ?? '')},
      city: ${q(d.address?.city ?? '')},
      state: ${q(d.address?.region ?? '')},
      zip: ${q(d.address?.postalCode ?? '')},
    },
    mapUrl: '',
    social: {
      facebook: ${q(d.social?.facebook ?? '')},
      instagram: ${q(d.social?.instagram ?? '')},
    },
  },

  // ── Hours ──
  hours: [
${formatHours(d.hours)}  ],
  hoursNote: '',

  // ── Branding ──
  colors: {
    primary: ${q(result.designBrief.colorPalette.value.primary)},
    secondary: ${q(result.designBrief.colorPalette.value.secondary)},
    accent: ${q(result.designBrief.colorPalette.value.accent)},
    highlight: ${q(result.designBrief.colorPalette.value.highlight)},
    background: ${q(result.designBrief.colorPalette.value.background)},
    foreground: ${q(result.designBrief.colorPalette.value.foreground)},
    muted: ${q(result.designBrief.colorPalette.value.muted)},
  },
  typography: {
    displayFont: ${q(result.designBrief.typography.value.display.family)},
    bodyFont: ${q(result.designBrief.typography.value.body.family)},
  },

  // ── Credentials ──
  credentials: {
    licensed: ${d.certifications && d.certifications.length > 0 ? 'true' : 'false'},
    insured: ${d.insuranceAmount ? 'true' : 'false'},
    insuranceAmount: ${q(d.insuranceAmount ?? '')},
    licenseNumber: ${q(d.certifications?.[0] ?? '')},
    certifications: [
${(d.certifications ?? []).map((c) => `      ${q(c)},`).join('\n')}
    ],
  },

  // ── Hero ──
  hero: {
    headline: ${q(d.name)},
    subheadline: ${q(g.businessStory.value.heroSubhead)},
    image: {
      src: '/images/hero.jpg',
      alt: ${q(`${d.name} — ${d.address?.city ?? 'local'} landscaping`)},
    },
  },

  // ── Section copy ──
  sectionCopy: {
    whyChooseUs: {
      heading: ${q(sc.whyChooseUs.heading)},
      intro: ${q(sc.whyChooseUs.intro)},
    },
    services: {
      eyebrow: ${q(sc.services.eyebrow ?? 'What we do')},
      heading: ${q(sc.services.heading)},
      intro: ${q(sc.services.intro)},
    },
    cta: {
      eyebrow: ${q(sc.cta.eyebrow ?? 'Free estimate')},
      heading: ${q(sc.cta.heading)},
      intro: ${q(sc.cta.intro)},
    },
    contact: {
      eyebrow: ${q(sc.contact.eyebrow ?? 'Free estimate')},
      heading: ${q(sc.contact.heading)},
      intro: ${q(sc.contact.intro)},
    },
  },

  // ── CTA style ──
  ctaStyle: {
    primary: ${q(g.ctaStyle.value.primary)},
    secondary: ${q(g.ctaStyle.value.secondary)},
    form: ${q(g.ctaStyle.value.form)},
    micro: ${q(g.ctaStyle.value.micro)},
  },

  // ── Business story ──
  businessStory: {
    founding: ${q(g.businessStory.value.founding)},
    mission: ${q(g.businessStory.value.mission)},
    differentiator: ${q(g.businessStory.value.differentiator)},
  },

  // ── Proof points ──
  proofPoints: [
${formatProofPoints(g.proofPoints.value)}  ],

  // ── Services ──
  services: [
${formatServices(g.services.value)}  ],

  // ── Benefits ──
  benefits: [
${formatBenefits(g.benefits.value)}  ],

  // ── Stats ──
  stats: [
${formatStats(g.stats.value)}  ],

  // ── Testimonials ──
  testimonials: [
${formatTestimonials(d.existingTestimonials)}  ],

  // ── Gallery ──
  gallery: [],

  // ── FAQ ──
  faq: [
${formatFAQ(g.faq.value)}  ],

  // ── Guarantee ──
  guarantee: {
    title: 'Our promise',
    body: ${q(g.businessStory.value.differentiator)},
  },

  // ── Financing ──
  financing: {
    available: false,
    note: '',
  },

  // ── Emergency service ──
  emergencyService: {
    available: ${d.hasEmergencyService ? 'true' : 'false'},
    tagline: ${d.hasEmergencyService ? q(g.urgency.value ?? '24/7 emergency response available') : "''"},
  },

  // ── Service towns ──
  serviceTowns: [
${(d.serviceTowns ?? []).map((t) => `    ${q(t)},`).join('\n')}
  ],
  serviceArea: ${q(d.serviceArea ?? '')},
  county: ${q(d.county ?? '')},

  // ── Process steps ──
  processSteps: [
    { step: 1, title: 'Request a quote', description: 'Fill out the form or call us. You'll have a written estimate within 24 hours.' },
    { step: 2, title: 'We get to work', description: 'Your dedicated crew arrives on schedule and handles every detail.' },
    { step: 3, title: 'Enjoy your property', description: 'Consistent results, same crew, no surprises — every time.' },
  ],

  // ── Engine intelligence ──
  _pipeline: {
    generatedAt: ${q(new Date().toISOString())},
    version: '1.0',
  },
} as const satisfies Business;
`;
}

// ─── Formatting helpers ───────────────────────────────────────────────────────

/** Single-quote-safe JSON string */
function q(s: string): string {
  return JSON.stringify(s);
}

function toSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function formatHours(hours?: Array<{ day: string; time: string }>): string {
  if (!hours || hours.length === 0) {
    return [
      "    { day: 'Monday–Friday', time: '7:00 AM – 6:00 PM' },\n",
      "    { day: 'Saturday', time: '8:00 AM – 4:00 PM' },\n",
      "    { day: 'Sunday', time: 'Closed' },\n",
    ].join('');
  }
  return hours.map((h) => `    { day: ${q(h.day)}, time: ${q(h.time)} },\n`).join('');
}

function formatProofPoints(points: PipelineProofPoint[]): string {
  return points
    .map(
      (p) =>
        `    { icon: ${p.iconName}, label: ${q(p.label)}, detail: ${q(p.detail)}${p.computed ? `, computed: ${q(p.computed)}` : ''} },\n`,
    )
    .join('');
}

function formatServices(services: PipelineServiceEntry[]): string {
  return services
    .map(
      (s) =>
        `    {\n` +
        `      slug: ${q(s.slug)},\n` +
        `      title: ${q(s.title)},\n` +
        (s.displayTitle ? `      displayTitle: ${q(s.displayTitle)},\n` : '') +
        `      summary: ${q(s.summary)},\n` +
        `      details: ${q(s.details)},\n` +
        `      includes: [\n` +
        s.includes.map((inc) => `        ${q(inc)},\n`).join('') +
        `      ],\n` +
        `      icon: ${s.iconName},\n` +
        `    },\n`,
    )
    .join('');
}

function formatBenefits(benefits: PipelineBenefit[]): string {
  return benefits
    .map(
      (b) =>
        `    { icon: ${b.iconName}, title: ${q(b.title)}, description: ${q(b.description)} },\n`,
    )
    .join('');
}

function formatStats(stats: PipelineStat[]): string {
  return stats.map((s) => `    { value: ${q(s.value)}, label: ${q(s.label)} },\n`).join('');
}

function formatTestimonials(
  testimonials?: Array<{
    quote: string;
    author?: string;
    location?: string;
    rating?: number;
    service?: string;
  }>,
): string {
  if (!testimonials || testimonials.length === 0) return '';
  return testimonials
    .map(
      (t) =>
        `    {\n` +
        `      quote: ${q(t.quote)},\n` +
        `      author: ${q(t.author ?? '')},\n` +
        `      location: ${q(t.location ?? '')},\n` +
        `      rating: ${t.rating ?? 5},\n` +
        (t.service ? `      service: ${q(t.service)},\n` : '') +
        `    },\n`,
    )
    .join('');
}

function formatFAQ(faq: PipelineFAQItem[]): string {
  return faq
    .map((f) => `    { question: ${q(f.question)}, answer: ${q(f.answer)} },\n`)
    .join('');
}

// ─── Confidence JSON ──────────────────────────────────────────────────────────

function generateConfidenceJson(report: ConfidenceReport): string {
  const summary = {
    generatedAt: new Date().toISOString(),
    totalFields: Object.keys(report).length,
    flaggedFields: Object.values(report).filter((e) => e.flagged).length,
    averageScore:
      Object.values(report).reduce((sum, e) => sum + e.score, 0) / Object.keys(report).length,
    fields: report,
  };
  return JSON.stringify(summary, null, 2);
}

// ─── Review queue markdown ────────────────────────────────────────────────────

function generateReviewQueueMd(queue: ReviewQueueItem[]): string {
  if (queue.length === 0) {
    return `# Review Queue\n\nAll fields passed confidence threshold. No review required.\n`;
  }

  const mustRewrite = queue.filter((i) => i.severity === 'must-rewrite');
  const shouldVerify = queue.filter((i) => i.severity === 'should-verify');
  const quickConfirm = queue.filter((i) => i.severity === 'quick-confirm');

  const formatItem = (item: ReviewQueueItem): string => {
    const lines = [
      `### \`${item.field}\``,
      `**Score:** ${(item.score * 100).toFixed(0)}% · **Source:** ${item.source}`,
      '',
      `**Current value:**`,
      '```',
      typeof item.currentValue === 'string'
        ? item.currentValue
        : JSON.stringify(item.currentValue, null, 2),
      '```',
    ];
    if (item.hint) {
      lines.push('', `**Hint:** ${item.hint}`);
    }
    if (item.alternatives && item.alternatives.length > 0) {
      lines.push('', '**Alternatives:**');
      (item.alternatives as string[]).forEach((alt, i) => {
        lines.push(`${i + 1}. ${typeof alt === 'string' ? alt : JSON.stringify(alt)}`);
      });
    }
    return lines.join('\n');
  };

  const sections: string[] = [
    `# Review Queue`,
    ``,
    `Generated: ${new Date().toISOString().split('T')[0]}`,
    ``,
    `**${mustRewrite.length} must-rewrite · ${shouldVerify.length} should-verify · ${quickConfirm.length} quick-confirm**`,
    ``,
    `---`,
  ];

  if (mustRewrite.length > 0) {
    sections.push(``, `## Must Rewrite`, `*Score below 40% — AI had insufficient context. Replace with accurate content.*`, ``);
    sections.push(...mustRewrite.map(formatItem));
  }

  if (shouldVerify.length > 0) {
    sections.push(``, `## Should Verify`, `*Score 40–59% — AI-generated from limited signals. Verify facts before publishing.*`, ``);
    sections.push(...shouldVerify.map(formatItem));
  }

  if (quickConfirm.length > 0) {
    sections.push(``, `## Quick Confirm`, `*Score 60–69% — Likely accurate but worth a second read. Tweak wording if needed.*`, ``);
    sections.push(...quickConfirm.map(formatItem));
  }

  return sections.join('\n');
}

// ─── Design brief markdown ────────────────────────────────────────────────────

function generateDesignBriefMd(brief: DesignBrief, businessName: string): string {
  const { colorPalette: { value: palette }, typography: { value: fonts }, buttonRadius, visualRegister, rationale } = brief;

  return `# Design Brief — ${businessName}

Generated: ${new Date().toISOString().split('T')[0]}

---

## Visual Register

**${visualRegister}** — ${rationale}

---

## Color Palette

${brief.colorPalette.flagged ? `> **Review required** (confidence: ${(brief.colorPalette.score * 100).toFixed(0)}%) — Verify against client's actual logo before implementing.` : ''}

| Token | Hex | Usage |
|-------|-----|-------|
| \`--color-primary\` | \`${palette.primary}\` | Primary brand color, main buttons |
| \`--color-secondary\` | \`${palette.secondary}\` | Dark backgrounds, footer |
| \`--color-accent\` | \`${palette.accent}\` | Highlights, icons, links |
| \`--color-highlight\` | \`${palette.highlight}\` | Hover states, secondary actions |
| \`--color-background\` | \`${palette.background}\` | Page background |
| \`--color-foreground\` | \`${palette.foreground}\` | Body text |
| \`--color-muted\` | \`${palette.muted}\` | Secondary text, captions |

---

## Typography

${brief.typography.flagged ? `> **Review required** (confidence: ${(brief.typography.score * 100).toFixed(0)}%) — Typography selection is based on visual register only, not logo analysis.` : ''}

| Role | Family | CSS Variable |
|------|--------|-------------|
| Display | ${fonts.display.family} | \`${fonts.display.cssVariable}\` |
| Body | ${fonts.body.family} | \`${fonts.body.cssVariable}\` |

**Fallback stack — Display:** ${fonts.display.fallback.join(', ')}
**Fallback stack — Body:** ${fonts.body.fallback.join(', ')}

---

## Button Radius

\`${buttonRadius}\`

---

## Logo Colors

${brief.logoColors.length > 0 ? brief.logoColors.map((c) => `- \`${c}\``).join('\n') : '_Not yet extracted. Provide logo file path in PipelineInput to enable automated extraction._'}

---

## Implementation Steps

1. Copy color tokens into \`src/lib/theme.ts\`
2. Install and configure ${fonts.display.family} + ${fonts.body.family} in \`layout.tsx\`
3. Review flagged palette against the actual logo
4. Test all buttons for WCAG AA contrast against backgrounds
`;
}

// ─── Photo brief markdown ─────────────────────────────────────────────────────

function generatePhotoBriefMd(brief: PhotoBrief, businessName: string): string {
  const required = brief.shots.filter((s) => s.priority === 'required');
  const recommended = brief.shots.filter((s) => s.priority === 'recommended');
  const optional = brief.shots.filter((s) => s.priority === 'optional');

  const formatShot = (s: PhotoShot): string => {
    const lines = [
      `### ${s.filename}`,
      `**Usage:** ${s.usage}`,
      `**Dimensions:** ${s.dimensions}`,
      ``,
      `**Framing:** ${s.framing}`,
    ];
    if (s.existingCandidate) {
      lines.push(``, `**Existing candidate (from GBP):** [${s.existingCandidate}](${s.existingCandidate})`);
    }
    return lines.join('\n');
  };

  const sections = [
    `# Photo Brief — ${businessName}`,
    ``,
    `Generated: ${new Date().toISOString().split('T')[0]}`,
    ``,
    `**${brief.totalRequired} required · ${recommended.length} recommended · ${optional.length} optional**`,
    `**${brief.totalFromGBP} existing photos found in GBP**`,
    ``,
    `---`,
  ];

  if (required.length > 0) {
    sections.push(``, `## Required Photos`, `*Must be provided before the site can go live.*`, ``);
    sections.push(...required.map(formatShot));
  }

  if (recommended.length > 0) {
    sections.push(``, `## Recommended Photos`, `*Strongly advised for a polished result.*`, ``);
    sections.push(...recommended.map(formatShot));
  }

  if (optional.length > 0) {
    sections.push(``, `## Optional Photos`, ``, ...optional.map(formatShot));
  }

  if (brief.existingPhotos.length > 0) {
    sections.push(``, `## Existing GBP Photos`, ``);
    for (const p of brief.existingPhotos) {
      sections.push(`- **${p.category}**: ${p.url} → _suitable for: ${p.suitableFor}_`);
    }
  }

  return sections.join('\n');
}
